# Generated by Django 5.2.8 on 2025-11-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_etiqueta_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
